learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls'))
]

learning_logs/urls.py
#Defines URL patterns for learning_logsself.
from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    #Detail Page
    path('topics/<int:topic_id>/', views.topic, name='topic')
]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    #A topic I am learning about
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        #return string representation of models
        return self.text

class Entry(models.Model):
    #Something specific learned about a topicself.
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        #Return a string representation of the modelself.
        if(len(self.text) > 50):
            return f"{self.text[:50]}..."
        else:
            return f"{self.text[:50]}"

learning_logs/views.py
from django.shortcuts import render

from .models import Topic

# Create your views here.
def index(request):
    #Home page for learning blog
    return render(request, 'learning_logs/index.html')

def topics(request):
    #Show all topics.
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html',context)


def topic(request, topic_id):
    #Show all topics.
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html',context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
      <title>Learning Log</title>

      {% bootstrap_css %}
      {% bootstrap_javascript jquery='full' %}
</head>
<body>

<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
  <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
    Learning Log</a>

  <button type="button" class="navbar-toggler" data-toggle="collapse"
  data-target="#navbarCollapse" aria-controls="navbarCollapse"
  aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span></button>
<div class="collapse navbar-collapse" id="navbarCollapse">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'learning_logs:topics'%}">
        Topics</a></li>
      </ul>

</nav>
<main role="main" class="container">
  <div class="pb-2 mb-2 border-bottom">
    <p>
      <a href="{% url 'learning_logs:index' %}">Learning Log</a>
      <a href="{% url 'learning_logs:topics' %}">Topics Log</a>
    </p>
    </div>
    <div >
      {% block content %}{% endblock content %}

    </div>
    </main>



</body>

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
<div class="jumbotron">
 <h1 class="display-3">Track your learning.</h1>
 <p class="lead">Make your own Learning Log, and keep a list of the
topics you're learning about. Whenever you learn something new
about a topic, make an entry summarizing what you've learned.</p>

</div>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>Topic {{ topic }}</p>

<p>EntriesL</p>
<ul>
  {% for entry in entries %}
    <li><p>{{ entry.date_added|date:'M d, Y H:i'}}</p>
        <p>{{ entry.text|linebreaks}}</p>
    </li>
    {% empty %}
      <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Topics</p>


<ul>
  {% for topic in topics %}
  <li>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}